### ISSUE TITLE
Problem with new kafka version

### ISSUE THREAD

**Issue by bitnulleins** [fhussonnois/kafkastreams-cep#1]
Hey!

Thank you for the great idea of CEP with Kafka Stream. Unfortunately your program only works for version 0.10. Is it possible to fix the problem and make it compatible with Kafka Stream 0.10.2? 

I get an "MethodNotFound" exception for the constructor call CEPStream. The signature of the abstract stream has change...

Thanks!

**Comment by fhussonnois** [comment]
Hi,

Yes, there is a regression on the AbstractStream class. This will be fixed in next release (https://github.com/apache/kafka/commit/c9f777cc44269c2e9537eab2451481422e613383).

In meanwhile, you can still directly use the Processor API.
I will update KakaStreamsCEP as soon as possible.

**Comment by bitnulleins** [comment]
Thank you!
